SET source_type=zip
SET source_official_tag=HEAD
SET source_git_url=foo
SET version_major=1
SET version_minor=2
SET version_build=34
SET name=Goliath Messenger
SET name_safe=Goliath Messenger
SET homepage_url=http://www.example.net/goliath
SET company=http://www.example.net/
SET guid={51291379-A1A5-4FDD-97EF-A5FB9BBB2A87}
SET support_url=http://www.example.net/support/goliath
SET info_url=http://www.example.net/goliath
